### ISSUE TITLE
Theme FileContentPreview plugin

### ISSUE THREAD

**Issue by DokterKaj** [rose-pine/discord-mobile#10]
There are some theming issues with FileContentPreview. I'm not sure whether it's the plugin's fault or the theme's fault, but here they are anyway.

"Preview" should be dark like the rest of the text on buttons:
![Screenshot_20240817-103106](https://github.com/user-attachments/assets/9c2a5402-2228-43a5-a6a1-7b1269118c94)

Close button in top left is hard to see, the toggles use Pine instead of Foam (#8):
![Screenshot_20240817-103140](https://github.com/user-attachments/assets/abc2f0af-4f36-40a2-b977-714a8d8fabc6)

Whatever's going on with the jump popup:
![Screenshot_20240817-103730](https://github.com/user-attachments/assets/faabb224-6d8a-4471-bcf4-7f9f03566d3e)

**Comment by mudrhiod** [comment]
The buttons and modals are also themed by the same string I mentioned on the previous post (I hate this app). The close button I'll have to find the name of and theme with themes+
