### ISSUE TITLE
[Rose Pine Moon] disable background image?

### ISSUE THREAD

**Issue by ccrowles** [rose-pine/discord-mobile#2]
Hi! Sorry to bother, but I noticed that you added a background image to Rose Pine Moon. While very cute, it's quite distracting for me, so I wanted to ask if there's any way to disable it, I'd prefer to go back to having the usual mono-color background without distracting patterns.

Sorry for the trouble and thanks in advance!

**Comment by mudrhiod** [comment]
No sorry

**Comment by ccrowles** [comment]
Understood, thanks.

**Comment by mudrhiod** [comment]
If you really want it removed then fork this repo. Go to the forked repo you made, click the theme.json for the theme you want background removed from, click "edit in place" and remove:
`    "background": {
        "alpha": 5,
        "url": "https://raw.githubusercontent.com/Quinxxxx/vendetta/main/Assets/V06yN.png"
    },`

**Comment by ccrowles** [comment]
I followed your advice and it works perfectly, thank you!
