### ISSUE TITLE
Pyoncord (aka Bunny) compatibility?

### ISSUE THREAD

**Issue by ccrowles** [rose-pine/discord-mobile#3]
Now that Bunny finally has an installer (and with the EOS of Vendetta and Revenge, making Bunny the only up-to-date alternative), do you plan to add support/maintain compatibility with Bunny?
Asking because on my (now buggy) Vendetta app the theme Rose Pine Moon looks very different than on Bunny

![Screenshot_20240530-151820](https://github.com/rose-pine/discord-mobile/assets/12866474/225312da-ab27-48fb-ad62-0265bb2c1743)
![Screenshot_20240530-151837](https://github.com/rose-pine/discord-mobile/assets/12866474/297aa1cf-9a58-4eda-ae6f-450cdddc1ae7)

(1st one is Vendetta, 2nd one is Bunny)

**Comment by mudrhiod** [comment]
Themes made for Vendetta don't really need to be changed to work on bunny, the themes kinda just broke (discord moment) with updates. I'll fix when I get time dw

**Comment by ccrowles** [comment]
Thank you, and sorry for the bother! Should I close the issue?
