### ISSUE TITLE
Rose Pine: Distinguish expanded folder background

### ISSUE THREAD

**Issue by DokterKaj** [rose-pine/discord-mobile#4]
The background for expanded folders is either invisible or the same colour as the navbar. Can it be distinguished?

Screenshot for reference:
![Screenshot_20240816-225134](https://github.com/user-attachments/assets/53822512-51fe-41dd-8efa-8efb898b6aaf)

**Comment by mudrhiod** [comment]
Yes sorry, I stopped with maintaining/making themes for vendetta/bunny so these themes are pretty outdated (even in the ss you attached things are themes wrongly due to discord internal changes.) My apolocheese, if I ever go back into theming I'll be sure to update these (if no one else does)

**Comment by DokterKaj** [comment]
Really? This is genuinely the best Vendetta theme I've found; I was trying out a ton of themes and anything updated less than six months ago was guaranteed to be broken. Thank you for your efforts (:

I'll report a few more issues I've found in the meantime

**Comment by mudrhiod** [comment]
> Really? This is genuinely the best Vendetta theme I've found; I was trying out a ton of themes and anything updated less than six months ago was guaranteed to be broken. Thank you for your efforts (:

I'm glad you liked it :)). And yeh discord released tabsv2 so most themes did break and they used to be very annoying with string changes, there are some updated themes in the bunny support server or enmity tho

> I'll report a few more issues I've found in the meantime

That would be fine, I'll take a look at them and fix em if I get the chance (Maybe tonight if the boredom kicks in lol)
