### ISSUE TITLE
Rose Pine: Distinguish forum post buttons

### ISSUE THREAD

**Issue by DokterKaj** [rose-pine/discord-mobile#7]
When scrolling through a forum post, there will be a sticky bar at the top with various buttons like reactions, following, etc, as shown below. However, the buttons are coloured so similarly to the background that they basically blend in.
![Screenshot_20240817-011722~2](https://github.com/user-attachments/assets/e1640d0d-b670-44f1-8deb-314d119da285)
Scrolling to the very beginning of a forum post will show another bar that has buttons with more distinguished colours. (Why there are two bars in the first place that don't look the same is anybody's guess.)
![Screenshot_20240817-012604](https://github.com/user-attachments/assets/8d91548b-29b5-4fee-9609-2e07c81c0923)
I propose that the sticky bar's buttons should be coloured to match the beginning bar's buttons. Outlines could even be added too if they look better with them.

**Comment by mudrhiod** [comment]
Tried my best to fix these :)
