### ISSUE TITLE
Pine still used in some places instead of Foam after theme update

### ISSUE THREAD

**Issue by DokterKaj** [rose-pine/discord-mobile#8]
There may be more but here's what I've found:

Channel symbol at the very beginning of a channel:
![Screenshot_20240817-100241~2](https://github.com/user-attachments/assets/65cadf73-12af-4ba4-8f21-8ea8e59ed8e0)

Load more messages button (in the case of this one, the text should be changed to be dark to fit with the theme update)
![Screenshot_20240817-100343~2](https://github.com/user-attachments/assets/cae3c378-9319-44c7-b39a-b37273babc04)

Edit profile buttons in profile popout:
![Screenshot_20240817-100327~2](https://github.com/user-attachments/assets/e32e0dcb-9215-455d-93f3-6ac08c3fcca8)

**Comment by mudrhiod** [comment]
I think these are all themed by the same string, should I make them into foam instead?

**Comment by mudrhiod** [comment]
Is this fine? Also what colour should I use for links I really don't know 😭

![Screenshot_2024-08-17-11-15-08-91_572064f74bd5f9fa804b05334aa4f912](https://github.com/user-attachments/assets/88223f54-f0da-42a5-91e0-1fe1dcb4e798)
![Screenshot_2024-08-17-11-14-10-36_572064f74bd5f9fa804b05334aa4f912](https://github.com/user-attachments/assets/c938e249-9f75-4d76-89fc-b27c4b36ce24)
