### ISSUE TITLE
Icons at the top of the You tab hard to see

### ISSUE THREAD

**Issue by DokterKaj** [rose-pine/discord-mobile#9]
They should be light instead of dark.
![Screenshot_20240817-101423](https://github.com/user-attachments/assets/fbc1d318-6278-43ff-8d0a-5164def3fe3e)

**Comment by mudrhiod** [comment]
I can't do anything about that sorry, unless you want horrible contrast in many other places

**Comment by DokterKaj** [comment]
Is the text colour there the same as the one used for text in Foam-coloured buttons? If so, what do you think about reverting the buttons back to being Pine-coloured and then changing the text to white?

**Comment by mudrhiod** [comment]
I managed to find the string that themes this, only downside is it'll make the transparent bg in this ss a bit bright, do you reckon this is fine otherwise 
![Screenshot_2024-08-17-11-09-28-67_572064f74bd5f9fa804b05334aa4f912](https://github.com/user-attachments/assets/3e1a6ccf-969a-4010-a817-f641c1f25e13)
![Screenshot_2024-08-17-11-10-43-85_572064f74bd5f9fa804b05334aa4f912](https://github.com/user-attachments/assets/1bacae7c-0b0c-4d8f-8eaa-4496155a0f2f)

**Comment by mudrhiod** [comment]
Also changing the text to white will cause bad tex contrast in other places. You'd get similar issues with other colour pallets like catppuccin where bright accent colours need to use the darker background colours for better contrast but then you can't bcuz discord uses strings in an annoying way (discord not make life of a client mod themer hard challenge (fail))

**Comment by DokterKaj** [comment]
The old version of this theme had white text on pine buttons and it looked good though:
![Screenshot_20240817-184713~2](https://github.com/user-attachments/assets/7538f0d7-2f77-4fdd-813f-0bce2918723a)
Did it cause any problems in other places?

**Comment by mudrhiod** [comment]
I honestly can't remember, Discord has made so many string changes and I haven't been keeping up with them but most likely it either caused problems in other places or used a different string ¯\_(ツ)_/¯. The text for the button text is WHITE. If I make it use `text` it'll cause bad contrast in places like the notification badge, bot tags (afaik!!) Text in emoji context menus

**Comment by DokterKaj** [comment]
If there are compromises either way, then I think I'd prefer reverting the buttons and text back to pine and white respectively. The best way to avoid running into problems like this is probably to stick relatively close to Discord defaults constrast-wise (i.e. light text on darker buttons rather than dark text on lighter buttons). Unless there's a reason why dark text on foam is preferred over light text on pine?

**Comment by mudrhiod** [comment]
Bcuz the string that themes the text is used in so many other places that are More noticable. Changing it to light colour would cause contrast issues in more noticeable places
